@echo off
echo Cleaning node_modules folder...
rmdir /s /q node_modules
echo Cleaning package-lock.json...
del package-lock.json
echo Installing dependencies...
npm install
echo Installation complete. Run 'npm run dev' to start the development server.
